#pragma once
#include <string>
#include <unordered_map>
enum IO_REG {
  JOYPAD      = 0x00,
  SB          = 0x01,
  SC          = 0x02,
  UNUSED_FF03 = 0x03,
  DIV         = 0x04,
  TIMA        = 0x05,
  TMA         = 0x06,
  TAC         = 0x07,
  IF          = 0x0F,
  NR10        = 0x10,
  NR11        = 0x11,
  NR12        = 0x12,
  NR13        = 0x13,
  NR14        = 0x14,
  NR15        = 0x15,
  NR21        = 0x16,
  NR22        = 0x17,
  NR23        = 0x18,
  NR24        = 0x19,
  NR30        = 0x1A,
  NR31        = 0x1B,
  NR32        = 0x1C,
  NR33        = 0x1D,
  NR34        = 0x1E,
  NR41        = 0x20,
  NR42        = 0x21,
  NR43        = 0x22,
  NR44        = 0x23,
  NR50        = 0x24,
  NR51        = 0x25,
  NR52        = 0x26,
  LCDC        = 0x40,
  STAT        = 0x41,
  SCY         = 0x42,
  SCX         = 0x43,
  LY          = 0x44,
  LYC         = 0x45,
  DMA         = 0x46,
  BGP         = 0x47,
  OBP0        = 0x48,
  OBP1        = 0x49,
  WY          = 0x4A,
  WX          = 0x4B,

  //  CGB
  KEY0 = 0x4C,  // backwards compat reg
  KEY1 = 0x4D,  // speed change
  VBK  = 0x4F,

  // VRAM DMA source high
  HDMA1 = 0x51,

  // VRAM DMA source low
  HDMA2 = 0x52,

  // VRAM DMA destination high
  HDMA3 = 0x53,

  // VRAM DMA destination low
  HDMA4 = 0x54,

  // VRAM DMA length/mode/start
  HDMA5 = 0x55,

  RP    = 0x56,
  BCPS  = 0x68,
  BCPD  = 0x69,
  OCPS  = 0x6A,
  OCPD  = 0x6B,
  OPRI  = 0x6C,
  SVBK  = 0x70,
  PCM12 = 0x76,
  PCM34 = 0x77,

  IE = 0xFF
};

const std::unordered_map<IO_REG, const std::string> IO_LABEL_MAP = {
    {     JOYPAD,      "JOYPAD"},
    {         SB,          "SB"},
    {         SC,          "SC"},
    {UNUSED_FF03, "UNUSED_FF03"},
    {        DIV,         "DIV"},
    {       TIMA,        "TIMA"},
    {        TMA,         "TMA"},
    {        TAC,         "TAC"},
    {         IF,          "IF"},
    {       NR10,        "NR10"},
    {       NR11,        "NR11"},
    {       NR12,        "NR12"},
    {       NR13,        "NR13"},
    {       NR14,        "NR14"},
    {       NR21,        "NR21"},
    {       NR22,        "NR22"},
    {       NR23,        "NR23"},
    {       NR24,        "NR24"},
    {       NR30,        "NR30"},
    {       NR31,        "NR31"},
    {       NR32,        "NR32"},
    {       NR33,        "NR33"},
    {       NR34,        "NR34"},
    {       NR41,        "NR41"},
    {       NR42,        "NR42"},
    {       NR43,        "NR43"},
    {       NR44,        "NR44"},
    {       NR50,        "NR50"},
    {       NR51,        "NR51"},
    {       NR52,        "NR52"},
    {       LCDC,        "LCDC"},
    {       STAT,        "STAT"},
    {        SCY,         "SCY"},
    {        SCX,         "SCX"},
    {         LY,          "LY"},
    {        LYC,         "LYC"},
    {        DMA,         "DMA"},
    {        BGP,         "BGP"},
    {       OBP0,        "OBP0"},
    {       OBP1,        "OBP1"},
    {         WY,          "WY"},
    {         WX,          "WX"},

    {       KEY0,        "KEY0"},
    {       KEY1,        "KEY1"},
    {        VBK,         "VBK"},
    {      HDMA1,       "HDMA1"},
    {      HDMA2,       "HDMA2"},
    {      HDMA3,       "HDMA3"},
    {      HDMA4,       "HDMA4"},
    {      HDMA5,       "HDMA5"},
    {         RP,          "RP"},
    {       BCPS,        "BCPS"},
    {       BCPD,        "BCPD"},
    {       OCPS,        "OCPS"},
    {       OCPD,        "OCPD"},
    {       OPRI,        "OPRI"},
    {       SVBK,        "SVBK"},
    {      PCM12,       "PCM12"},
    {      PCM34,       "PCM34"},
    {         IE,          "IE"},
};