name: CPU Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
          mkdir build/bin
          sudo apt-get update
          sudo apt-get install -y build-essential
    - name: make check
      run: make check
